@istest

Public class FromContact_Activate_test{


Public static testmethod void FromContactActivate1(){

    test.starttest();
       /*
        Test_InsertFirm_Contact_Team_TeamRole.testCreateAccount ();
       
       StatusChangeHandler.STATUSCHANGETRIGGER = false;
       Contact[] lstContact = [Select id,Status__c From Contact];     
       lstContact[0].Status__c ='Inactive';
       Update lstContact;
       
       lstContact[0].Status__c ='Active';
       Update lstContact;
       */
    
    test.stoptest();
    

}



}