Public Class FromFirmTeam_Deactivate{


//@invocablemethod
Public static Boolean DactivateAllMembers(List<Id> FirmTeam){
/*
    Boolean Active=FirmMemberTeamHandler.CheckForActiveTeam(FirmTeam);
    
    if(Active){
        
    }
    
    else{ 
        FirmMemberTeamHandler.DecativeAllmembersinteam(FirmTeam);
    }
  
    
    FirmMemberTeamHandler.DecativeAllmembersinteam(FirmTeam);
*/
    return  false;    
}


}